templates:
  Карта для путешествий:
    - "{first_name}, в {month} вы много тратили на поездки. С нашей тревел-картой часть расходов вернулась бы вам кешбэком. Хотите оформить?"
    - "Видим, вы цените поездки, {first_name}. Только в {month} вы могли бы сэкономить до {benefit_value} с нашей картой для путешествий. Оформить сейчас."

  Премиальная карта:
    - "{first_name}, у вас стабильно крупный остаток и частые траты в ресторанах. Карта Premium даст повышенный кешбэк и бесплатные снятия. Оформить карту."
    - "Здравствуйте, {first_name}. Ваши траты и средний баланс позволяют получать больше выгоды. Оформите карту Premium и возвращайте до {benefit_value} в месяц. Попробовать."

  Кредитная карта:
    - "{first_name}, ваши топ-категории — {cat1} и {cat2}. Наша кредитная карта даёт до 10% в любимых категориях и на онлайн-сервисы. Оформить карту."
    - "Привет, {first_name}. Заметили, что вы часто покупаете в категориях «{cat1}» и «{cat2}». С нашей кредитной картой это было бы еще выгоднее. Узнать больше."

  Обмен валют:
    - "{first_name}, вы часто платите в {fx_curr}. В нашем приложении выгодный обмен и автопокупка по целевому курсу. Настроить обмен."
    - "Меняете {fx_curr}? {first_name}, с нашим сервисом вы могли бы экономить до {benefit_value} в месяц на комиссиях. Попробовать сейчас."

  Депозит Мультивалютный:
    - "{first_name}, видим, у вас есть накопления в разных валютах. Разместите их на мультивалютном депозите для удобного управления и дохода. Открыть вклад."

  Депозит Сберегательный:
    - "{first_name}, у вас остаются свободные средства. Разместите их на сберегательном вкладе с максимальной ставкой для приумножения. Открыть вклад."

  Депозит Накопительный:
    - "{first_name}, видим, что вы регулярно откладываете. С накопительным вкладом копить на ваши цели станет еще проще и выгоднее. Открыть вклад."

  Инвестиции:
    - "{first_name}, попробуйте инвестиции с порогом входа от 6 ₸ и без комиссий на старте. Ваши свободные средства могут приносить доход. Открыть счёт."
    - "Здравствуйте, {first_name}. Заметили, что у вас есть свободные средства. Инвестируйте их в акции и фонды без комиссий на старте. Начать инвестировать."

  Кредит наличными:
    - "{first_name}, если нужен запас средств на крупные траты — можно оформить кредит наличными с гибкими условиями погашения. Узнать доступный лимит."

  Золотые слитки:
    - "{first_name}, для диверсификации и долгосрочного сохранения сбережений рассмотрите вложения в золотые слитки. Узнать больше."

  Generic:
    - "Здравствуйте, {first_name}. У нас есть несколько персональных предложений, которые могут вас заинтересовать. Узнайте больше в приложении."